### PR TITLE
feat: v2.3

### PR DESCRIPTION
**Pull request by WoodNeck**
## New Features
- Added `maintainSize`
- Enhanced `initialZoom` to accept object types so that it can fit model proportionally to canvas width/height

## Bug fix
- Fixed a bug that the camera doesn't respect skinned vertices
- Fixed zoom control range is controlled by motion so it wasn't able to zoom-in in some cases.
- Fixed a bug that iOS<12 can't handle envmaps due to half float data type.

Demo page: https://woodneck.github.io/egjs-view3d/

### CODE REVIEW

**Review by qpitlove — APPROVED** [review]
LGTM

**Review by daybrush — APPROVED** [review]
LGTM

**Comment by daybrush** [comment]
I have a question. When maintainSize is applied, is the model initially rendered according to the size of the canvas? Or is there an absolute size of the model?

**Comment by WoodNeck** [comment]
> I have a question. When maintainSize is applied, is the model initially rendered according to the size of the canvas? Or is there an absolute size of the model?

The initial rendering is the same as the original. `maintainSize` only applies after the first resize.
So, `the model initially rendered according to the size of the canvas` is correct.

**Review by malangfox — APPROVED** [review]
LGTM

**Pull request merged**
